# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/toshiba/tostab03/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
#PRODUCT_COPY_FILES := \
#    vendor/toshiba/tostab03/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
#    vendor/toshiba/tostab03/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
#    vendor/toshiba/tostab03/proprietary/lib/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
#    vendor/toshiba/tostab03/proprietary/lib/libseccameraadaptor.so:obj/lib/libseccameraadaptor.so

PRODUCT_COPY_FILES += \
    vendor/toshiba/tostab03/proprietary/framework/filterfw.jar:system/framework/filterfw.jar \
    vendor/toshiba/tostab03/proprietary/etc/vold.fstab:system/etc/vold.fstab \
    vendor/toshiba/tostab03/proprietary/etc/gps/gpsconfig.xml:system/etc/gps/gpsconfig.xml \
    vendor/toshiba/tostab03/proprietary/etc/toshdmi:system/etc/toshdmi \
    vendor/toshiba/tostab03/proprietary/etc/bluetooth/main.conf:system/etc/bluetooth/main.conf \
    vendor/toshiba/tostab03/proprietary/etc/bluetooth/auto_pairing.conf:system/etc/bluetooth/auto_pairing.conf \
    vendor/toshiba/tostab03/proprietary/etc/bluetooth/audio.conf:system/etc/bluetooth/audio.conf \
    vendor/toshiba/tostab03/proprietary/etc/bluetooth/bdaddr:system/etc/bluetooth/bdaddr \
    vendor/toshiba/tostab03/proprietary/etc/bluetooth/blacklist.conf:system/etc/bluetooth/blacklist.conf \
    vendor/toshiba/tostab03/proprietary/etc/bluetooth/input.conf:system/etc/bluetooth/input.conf \
    vendor/toshiba/tostab03/proprietary/etc/bluetooth/network.conf:system/etc/bluetooth/network.conf \
    vendor/toshiba/tostab03/proprietary/etc/nvram_4330.txt:system/etc/nvram_4330.txt \
    vendor/toshiba/tostab03/proprietary/etc/nvcamera.conf:system/etc/nvcamera.conf \
    vendor/toshiba/tostab03/proprietary/etc/model_frontal.xml:system/etc/model_frontal.xml \
    vendor/toshiba/tostab03/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/toshiba/tostab03/proprietary/etc/nvram_4329.txt:system/etc/nvram_4329.txt \
    vendor/toshiba/tostab03/proprietary/etc/egfv.cfg:system/etc/egfv.cfg \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/bcm4330.hcd:system/etc/firmware/bcm4330.hcd \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
    vendor/toshiba/tostab03/proprietary/etc/firmware/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
    vendor/toshiba/tostab03/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
    vendor/toshiba/tostab03/proprietary/etc/apns-conf.xml:system/etc/apns-conf.xml \
    vendor/toshiba/tostab03/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/toshiba/tostab03/proprietary/etc/wv.cfg:system/etc/wv.cfg \
    vendor/toshiba/tostab03/proprietary/etc/dhcpcd/dhcpcd.conf:system/etc/dhcpcd/dhcpcd.conf \
    vendor/toshiba/tostab03/proprietary/etc/dhcpcd/dhcpcd-run-hooks:system/etc/dhcpcd/dhcpcd-run-hooks \
    vendor/toshiba/tostab03/proprietary/etc/dhcpcd/dhcpcd-hooks/20-dns.conf:system/etc/dhcpcd/dhcpcd-hooks/20-dns.conf \
    vendor/toshiba/tostab03/proprietary/etc/dhcpcd/dhcpcd-hooks/95-configured:system/etc/dhcpcd/dhcpcd-hooks/95-configured \
    vendor/toshiba/tostab03/proprietary/etc/nvram.txt:system/etc/nvram.txt \
    vendor/toshiba/tostab03/proprietary/etc/asound.conf:system/etc/asound.conf \
    vendor/toshiba/tostab03/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/gps.tostab03.so:system/lib/hw/gps.tostab03.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/sensors.tostab03.so:system/lib/hw/sensors.tostab03.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/nfc.tegra.so:system/lib/hw/nfc.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/audio_policy.tegra.so:system/lib/hw/audio_policy.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/audio.primary.tegra.so:system/lib/hw/audio.primary.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/camera.tegra.so:system/lib/hw/camera.tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/lights.tostab03.so:system/lib/hw/lights.tostab03.so \
    vendor/toshiba/tostab03/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_asfparser.so:system/lib/libnvmm_asfparser.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
    vendor/toshiba/tostab03/proprietary/lib/libi2c_ctl.so:system/lib/libi2c_ctl.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
    vendor/toshiba/tostab03/proprietary/lib/libaudioservice.so:system/lib/libaudioservice.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
    vendor/toshiba/tostab03/proprietary/lib/libpega_runtime_jni.so:system/lib/libpega_runtime_jni.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
    vendor/toshiba/tostab03/proprietary/lib/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/toshiba/tostab03/proprietary/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
    vendor/toshiba/tostab03/proprietary/lib/libeglstreamtexture.so:system/lib/libeglstreamtexture.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_aviparser.so:system/lib/libnvmm_aviparser.so \
    vendor/toshiba/tostab03/proprietary/lib/modules/tun.ko:system/lib/modules/tun.ko \
    vendor/toshiba/tostab03/proprietary/lib/modules/bcmdhd.ko:system/lib/modules/bcmdhd.ko \
    vendor/toshiba/tostab03/proprietary/lib/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
    vendor/toshiba/tostab03/proprietary/lib/modules/bcm4329.ko:system/lib/modules/bcm4329.ko \
    vendor/toshiba/tostab03/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/toshiba/tostab03/proprietary/lib/egl/libGLESv2_perfhud.so:system/lib/egl/libGLESv2_perfhud.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libEGL_perfhud.so:system/lib/egl/libEGL_perfhud.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libGLESv1_CM_perfhud.so:system/lib/egl/libGLESv1_CM_perfhud.so \
    vendor/toshiba/tostab03/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/toshiba/tostab03/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/toshiba/tostab03/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
    vendor/toshiba/tostab03/proprietary/lib/libDmiService.so:system/lib/libDmiService.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvhdmi3dplay_jni.so:system/lib/libnvhdmi3dplay_jni.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_vc1_video.so:system/lib/libnvmm_vc1_video.so \
    vendor/toshiba/tostab03/proprietary/lib/libEGL.so:system/lib/libEGL.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvsystemuiext_jni.so:system/lib/libnvsystemuiext_jni.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvtestio.so:system/lib/libnvtestio.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvcontrol_jni.so:system/lib/libnvcontrol_jni.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_msaudio.so:system/lib/libnvmm_msaudio.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
    vendor/toshiba/tostab03/proprietary/lib/libGLESv2_dbg.so:system/lib/libGLESv2_dbg.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvos.so:system/lib/libnvos.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
    vendor/toshiba/tostab03/proprietary/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/toshiba/tostab03/proprietary/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
    vendor/toshiba/tostab03/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/toshiba/tostab03/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/toshiba/tostab03/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/toshiba/tostab03/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/toshiba/tostab03/proprietary/vendor/firmware/bcm4330/fw_bcmdhd_p2p.bin:system/vendor/firmware/bcm4330/fw_bcmdhd_p2p.bin \
    vendor/toshiba/tostab03/proprietary/vendor/firmware/bcm4330/fw_bcmdhd.bin:system/vendor/firmware/bcm4330/fw_bcmdhd.bin \
    vendor/toshiba/tostab03/proprietary/vendor/firmware/bcm4330/fw_bcmdhd_apsta.bin:system/vendor/firmware/bcm4330/fw_bcmdhd_apsta.bin \
    vendor/toshiba/tostab03/proprietary/vendor/firmware/bcm4329/fw_bcmdhd_p2p.bin:system/vendor/firmware/bcm4329/fw_bcmdhd_p2p.bin \
    vendor/toshiba/tostab03/proprietary/vendor/firmware/bcm4329/fw_bcmdhd.bin:system/vendor/firmware/bcm4329/fw_bcmdhd.bin \
    vendor/toshiba/tostab03/proprietary/vendor/firmware/bcm4329/fw_bcmdhd_apsta.bin:system/vendor/firmware/bcm4329/fw_bcmdhd_apsta.bin \
    vendor/toshiba/tostab03/proprietary/vendor/firmware/fw_bcm4329_apsta.bin:system/vendor/firmware/fw_bcm4329_apsta.bin \
    vendor/toshiba/tostab03/proprietary/vendor/firmware/fw_bcm4329.bin:system/vendor/firmware/fw_bcm4329.bin \
    vendor/toshiba/tostab03/proprietary/bin/dmiserver:system/bin/dmiserver \
    vendor/toshiba/tostab03/proprietary/bin/setup_fs:system/bin/setup_fs \
    vendor/toshiba/tostab03/proprietary/bin/rild:system/bin/rild \
    vendor/toshiba/tostab03/proprietary/bin/bdaddr2:system/bin/bdaddr2 \
    vendor/toshiba/tostab03/proprietary/bin/nvcpud:system/bin/nvcpud \
    vendor/toshiba/tostab03/proprietary/usr/share/zoneinfo/zoneinfo.idx:system/usr/share/zoneinfo/zoneinfo.idx \
    vendor/toshiba/tostab03/proprietary/usr/share/zoneinfo/zoneinfo.dat:system/usr/share/zoneinfo/zoneinfo.dat \
    vendor/toshiba/tostab03/proprietary/usr/share/zoneinfo/zoneinfo.version:system/usr/share/zoneinfo/zoneinfo.version \
    vendor/toshiba/tostab03/proprietary/usr/share/bmd/RFFspeed_501.bmd:system/usr/share/bmd/RFFspeed_501.bmd \
    vendor/toshiba/tostab03/proprietary/usr/share/bmd/RFFstd_501.bmd:system/usr/share/bmd/RFFstd_501.bmd \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
    vendor/toshiba/tostab03/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
    vendor/toshiba/tostab03/proprietary/usr/icu/icudt46l.dat:system/usr/icu/icudt46l.dat \
    vendor/toshiba/tostab03/proprietary/usr/keychars/Virtual.kcm:system/usr/keychars/Virtual.kcm \
    vendor/toshiba/tostab03/proprietary/usr/keychars/Generic.kcm:system/usr/keychars/Generic.kcm \
    vendor/toshiba/tostab03/proprietary/usr/keychars/qwerty.kcm:system/usr/keychars/qwerty.kcm \
    vendor/toshiba/tostab03/proprietary/usr/keychars/qwerty2.kcm:system/usr/keychars/qwerty2.kcm \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_046d_Product_c216.kl:system/usr/keylayout/Vendor_046d_Product_c216.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Bluetooth_00_06_66_42.kl:system/usr/keylayout/Bluetooth_00_06_66_42.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_057e_Product_0306.kl:system/usr/keylayout/Vendor_057e_Product_0306.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_046d_Product_c21f.kl:system/usr/keylayout/Vendor_046d_Product_c21f.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_05ac_Product_0239.kl:system/usr/keylayout/Vendor_05ac_Product_0239.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Generic.kl:system/usr/keylayout/Generic.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_046d_Product_c532.kl:system/usr/keylayout/Vendor_046d_Product_c532.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_046d_Product_c294.kl:system/usr/keylayout/Vendor_046d_Product_c294.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_045e_Product_028e.kl:system/usr/keylayout/Vendor_045e_Product_028e.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_054c_Product_0268.kl:system/usr/keylayout/Vendor_054c_Product_0268.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_046d_Product_c21d.kl:system/usr/keylayout/Vendor_046d_Product_c21d.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_22b8_Product_093d.kl:system/usr/keylayout/Vendor_22b8_Product_093d.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_045e_Product_0719.kl:system/usr/keylayout/Vendor_045e_Product_0719.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_046d_Product_c299.kl:system/usr/keylayout/Vendor_046d_Product_c299.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/Vendor_044f_Product_d007.kl:system/usr/keylayout/Vendor_044f_Product_d007.kl \
    vendor/toshiba/tostab03/proprietary/usr/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
    vendor/toshiba/tostab03/proprietary/usr/idc/atmel-maxtouch.idc:system/usr/idc/atmel-maxtouch.idc \
    vendor/toshiba/tostab03/proprietary/usr/idc/qwerty.idc:system/usr/idc/qwerty.idc \
    vendor/toshiba/tostab03/proprietary/usr/idc/egalax_i2c.idc:system/usr/idc/egalax_i2c.idc \
    vendor/toshiba/tostab03/proprietary/usr/idc/qwerty2.idc:system/usr/idc/qwerty2.idc \
    vendor/toshiba/tostab03/proprietary/usr/idc/panjit_touch.idc:system/usr/idc/panjit_touch.idc
